version: '3'

services:
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./my_data:/var/lib/postgresql
      - ./my_sqllogs:/var/log/postgresql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "55211:8000"
    depends_on:
      - db